# Generated by Django 4.1.5 on 2023-02-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Количество продукта')),
            ],
            options={
                'verbose_name': 'Таблица корзин пользователей2',
                'verbose_name_plural': 'Таблица корзин пользователей2',
                'db_table': 'cart2',
            },
        ),
    ]
