# Generated by Django 4.1.5 on 2023-02-01 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0002_cart2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.AlterModelOptions(
            name='cart2',
            options={'managed': False, 'verbose_name': 'Таблица корзин пользователей', 'verbose_name_plural': 'Таблица корзин пользователей'},
        ),
    ]
