# Generated by Django 4.1.5 on 2023-02-01 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0003_delete_cart_alter_cart2_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart2',
        ),
    ]
