# Generated by Django 4.1.5 on 2023-02-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0004_delete_cart2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='ID пользователя')),
                ('prod_id', models.IntegerField(verbose_name='ID продукта')),
                ('quantity', models.IntegerField(verbose_name='Количество продукта')),
            ],
            options={
                'verbose_name': 'Таблица корзин пользователей',
                'verbose_name_plural': 'Таблица корзин пользователей',
                'db_table': 'cart',
            },
        ),
    ]
