# Generated by Django 4.1.5 on 2023-02-02 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0005_cart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Корзина пользователя', 'verbose_name_plural': 'Таблица корзин пользователей'},
        ),
        migrations.AlterModelOptions(
            name='catalog',
            options={'managed': False, 'verbose_name': 'Товар', 'verbose_name_plural': 'Таблица товаров'},
        ),
        migrations.AlterModelOptions(
            name='people',
            options={'managed': False, 'verbose_name': 'Пользователь бота', 'verbose_name_plural': 'Пользователи бота'},
        ),
    ]
