# Generated by Django 4.1.5 on 2023-02-02 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0006_alter_cart_options_alter_catalog_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalog',
            options={'managed': True, 'verbose_name': 'Товар', 'verbose_name_plural': 'Таблица товаров'},
        ),
        migrations.AlterModelOptions(
            name='people',
            options={'managed': True, 'verbose_name': 'Пользователь бота', 'verbose_name_plural': 'Пользователи бота'},
        ),
    ]
