# Generated by Django 4.1.5 on 2023-02-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0007_alter_catalog_options_alter_people_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='prod_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID продукта'),
        ),
        migrations.AlterField(
            model_name='people',
            name='user_id',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID пользователя'),
        ),
    ]
