# Generated by Django 4.1.5 on 2023-02-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0009_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='processed',
            field=models.BooleanField(default=False, verbose_name='Заказ обработан'),
        ),
    ]
