# Generated by Django 4.1.5 on 2023-02-10 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0010_order_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='track_number',
            field=models.IntegerField(default=None, verbose_name='Трек номер пользователя'),
        ),
    ]
