# Generated by Django 4.1.5 on 2023-02-10 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0014_alter_order_track_number'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='orders',
        ),
    ]
