# Generated by Django 4.1.5 on 2023-02-10 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0015_alter_order_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
