# Generated by Django 4.1.5 on 2023-02-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0017_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='processed',
        ),
        migrations.AddField(
            model_name='order',
            name='send',
            field=models.BooleanField(default=False, verbose_name='Заказ отправлен'),
        ),
    ]
