# Generated by Django 4.1.5 on 2023-02-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0019_alter_order_track_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='send',
            new_name='is_order_send',
        ),
        migrations.AddField(
            model_name='order',
            name='is_track_number_send',
            field=models.BooleanField(default=False, verbose_name='Трек номер отправлен'),
        ),
    ]
