# Generated by Django 4.1.5 on 2023-02-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0022_alter_order_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_order_send',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Заказ отправлен'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_track_number_send',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Трек номер отправлен'),
        ),
    ]
