# Generated by Django 4.1.5 on 2023-02-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0023_alter_order_is_order_send_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_order_send',
            field=models.BooleanField(default=False, verbose_name='Заказ отправлен'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_track_number_send',
            field=models.BooleanField(default=False, verbose_name='Трек номер отправлен'),
        ),
    ]
